version: '2'
services:
  go:
    build:
      context: ./docker/go
    command: ./scripts/run-all-tests
    environment:
      GO111MODULE: "on"
    volumes:
     - .:/go/src/github.com/{{cookiecutter.github_org_or_user}}/{{cookiecutter.project}}
    working_dir: /go/src/github.com/{{cookiecutter.github_org_or_user}}/{{cookiecutter.project}}
